# tasks file for mailhog
---
- name: facts | set
  set_fact:
     is_docker_guest: "{{ ansible_virtualization_role | default('host') == 'guest' and ansible_virtualization_type | default('none') == 'docker' }}"
  tags:
    - configuration
    - mailhog
    - mailhog-facts

- include: install.yml
  tags:
    - configuration
    - mailhog
    - mailhog-install

- include: user.yml
  tags:
    - configuration
    - mailhog
    - mailhog-user

- include: configure.yml
  tags:
    - configuration
    - mailhog
    - mailhog-configure

- block:
    - include: service-initd.yml
  when: is_docker_guest
  tags:
    - configuration
    - mailhog
    - mailhog-service
    - mailhog-service-initd

- block:
    - include: service-upstart.yml
      when: ansible_service_mgr != 'systemd'
      tags:
        - mailhog-service-upstart

    - include: service-systemd.yml
      when: ansible_service_mgr == 'systemd'
      tags:
        - mailhog-service-systemd
  when: not is_docker_guest
  tags:
    - configuration
    - mailhog
    - mailhog-service

- name: start and enable service
  service:
    name: mailhog
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - mailhog
    - mailhog-start-enable-service
