# tasks file for mailhog
---
- name: create init script
  template:
    src: etc/init/mailhog.conf.j2
    dest: /etc/init/mailhog.conf
    owner: root
    group: root
    mode: 0644
  notify: restart mailhog
  tags:
    - mailhog-service-init

- name: start and enable service
  service:
    name: mailhog
    state: started
    enabled: true
  tags:
    - mailhog-service-start-enable
