# tasks file for mailhog
---
- name: service | initd | update script
  template:
    src: etc/init.d/mailhog.j2
    dest: /etc/init.d/mailhog
    owner: root
    group: root
    mode: 0755
  notify: restart mailhog
  tags:
    - mailhog-service-initd-update
