# tasks file for mailhog
---
- name: service | upstart | update script
  template:
    src: "{{ mailhog_etc_init_file.lstrip('/') }}.j2"
    dest: "{{ mailhog_etc_init_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mailhog
  tags:
    - mailhog-service-upstart-update
