# tasks file for mailhog
---
- name: service | systemd | update script
  template:
    src: "{{ mailhog_etc_systemd_file.lstrip('/') }}.j2"
    dest: "{{ mailhog_etc_systemd_file }}"
    owner: root
    group: root
    mode: 0644
  register: _update_systemd_script
  notify: restart mailhog
  tags:
    - mailhog-service-systemd-update

- name: service | systemd | reload
  command: systemctl daemon-reload
  when: _update_systemd_script is changed
  tags:
    - mailhog-service-systemd-reload
