# tasks file
---
- name: service | initd | update script
  ansible.builtin.template:
    src: "{{ mailhog_etc_init_d_file.lstrip('/') }}.j2"
    dest: "{{ mailhog_etc_init_d_file }}"
    owner: root
    group: root
    mode: 0755
  notify: restart mailhog
  tags:
    - mailhog-service-initd-update
