# tasks file for mailhog
---
- name: add group
  group:
    name: "{{ item }}"
  with_flattened:
    - "{{ mailhog_group }}"
    - "{{ mailhog_groups }}"
  tags:
    - mailhog-user-add
    - mailhog-user-add-group

- name: add user
  user:
    name: "{{ mailhog_user }}"
    group: "{{ mailhog_group }}"
    groups: "{{ mailhog_groups | join(',') }}"
    home: /var/mailhog
    shell: /bin/false
  tags:
    - mailhog-user-add
    - mailhog-user-add-user
