# tasks file
---
- name: add group
  ansible.builtin.group:
    name: "{{ item }}"
    system: true
  with_items: "{{ [mailhog_group] + mailhog_groups }}"
  tags:
    - mailhog-user-add
    - mailhog-user-add-group

- name: add user
  ansible.builtin.user:
    name: "{{ mailhog_user }}"
    system: true
    group: "{{ mailhog_group }}"
    groups: "{{ mailhog_groups | join(',') }}"
    home: /var/mailhog
    shell: /bin/false
  tags:
    - mailhog-user-add
    - mailhog-user-add-user
